Use clang-tidy to find performance issues
WolfireGames/overgrowth pull request #60
Opened 2022-05-04 10:56 UTC by feliwir

Use the [clang-tidy](https://clang.llvm.org/extra/clang-tidy) static code analyzer to find any performance issues within our source code. I've applied the following checks:
- [performance-faster-string-find](https://clang.llvm.org/extra/clang-tidy/checks/performance-faster-string-find.html): find any string find algorithms that can be improved

2022-05-06 03:34 UTC, Conan-Kudo commented on Source/Compat/processpool.cpp
> +for(int i=0; i<argc; ++i){
Broken indentation here.

2022-05-06 03:35 UTC, Conan-Kudo requested changes

2022-05-06 03:35 UTC, Conan-Kudo commented on Source/Scripting/angelscript/asfuncs.cpp
> +for( int n = 0; n < (int)array.GetSize(); n++ )
Broken indentation.

2022-05-06 03:35 UTC, Conan-Kudo commented on Source/Scripting/angelscript/asfuncs.cpp
> +for(int n = 0; n < items_count; ++n) {
Broken indentation.

2022-05-06 03:35 UTC, Conan-Kudo commented on Source/Scripting/angelscript/asfuncs.cpp
> +for(int n = 0; n < items_count; ++n) {
Broken indentation.

2022-05-06 07:06 UTC, feliwir commented
All review comments adressed & rebased

2022-05-06 11:24 UTC, Conan-Kudo approved these changes

2022-05-06 11:24 UTC, merged

2022-05-10 17:58 UTC, shinymerlyn commented on Source/Scripting/angelscript/add_on/scripthelper/scripthelper.cpp
> +				pos = str.find('\"',pos);
this code is inside angelscript I think? I believe these local patches may make it harder to diff when upgrading the angelscript version.

2022-05-10 17:58 UTC, shinymerlyn commented on Source/Scripting/angelscript/add_on/scripthelper/scripthelper.cpp
> +				pos = str.find('\"',pos);
or maybe this is a local "add-on". not sure if it's one of the standard ones or not.